CREATE TABLE IF NOT EXISTS chamado (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao text NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY id INTEGER NOT NULL REFERENCES responsavel(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS responsavel (
    id SERIAL PRIMARY KEY,
    nome Varchar(255) NOT NULL,
    email Varchar(255) NOT NULL UNIQUE,
    senha PASSWORD NOT NULL
);
