###

GET http://localhost:3000/responsavel

###

POST http://localhost:3000/responsavel
Content-Type: application/json

{
    "nome": "Vinícius Ferreira",
    "senha": "0711",
    "email": "karateka@gmail.com"
}

###

PUT http://localhost:3000/responsavel/1
Content-Type: application/json

{
    "nome": "alexandre",
    "email": "marquinhoLindo@gmail.com",
    "senha": "12345"
}

### Daqui pra baixo são os chamados

###
GET http://localhost:3000/chamados

###
POST http://localhost:3000/chamados
Content-Type: application/json

{
    "titulo": "Título genérico",
    "descricao": "Chamado INSERT",
    "id_responsavel": "1"
}


###
PUT http://localhost:3000/chamados/1
Content-Type: application/json

{
    "titulo": "SAMARA",
    "descricao": "Chamado UPDATE",
    "id_responsavel": "1"
}

###
DELETE http://localhost:3000/chamados/1

###
